---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: order-secrets
  namespace: ecommerce-dev
spec:
  encryptedData:
    PAYMENT_API_KEY: AgA/uDOa5r1dxiDg1YDWLhzreZzjhu8iT/6p2RvRb1DIs/GM+IlrRVtVFon2CCOz4Knvkocl2OrHsjFj5o5MuoliQn+FM/URjRT/pDYzWgTRDTadsJT3glf1HWv7V1ZnGoX2NvKHitelnlLslsoNA20y9147Ax3JKougcdLIzTQxAtHcRPjgj1B7f221bU/p+ymMpkeAl/jWGE4YScD7H3ldgie/5xl9wcsZECcI6+/dlIATxPFOpkKlKcZv2FCtC0XQb7YTmsx99Hr7nNKOTnsEDHcMFDiGhlbyXAw39IKeWucGzdycUQXEEpPRBHLQGY4BES25aCQZo0WHZ15++pJhjBu9t2M485Ac2L8IMjJhJok3NtL6gK98/yDPx18SECfKzax2/vlu2O4hMW3h4so65wOGBPyd2eKlPDlxc5VkN3+3PP78uHO2BeHiWRwTRAtN99zN6P9pKUlfAhbt8utRo714t/Did0HIRnjhgPORczQE0EGKarPIeFGmBf4WuX5fi2ZBr+zzLS2UTz/7Nv5q4aDdL+2oN62xJ0RBAjsH4BpCvxqyn0VuY88iCoQ02l0CCkjnafd073DS5jMVVJylsO0skUIA0YmFebibXzm1GocCtscoEI7AxaVDiWJ5jAqViTVSU/2cwS6pL+ZK9VkjRXtOh5C3m5d7Frm1j+M2u5u3hCQKIGnM2+G/LNvzKyfpqXBSkyzGSI5T/PhQkWCh6FcF/Lk=
  template:
    metadata:
      name: order-secrets
      namespace: ecommerce-dev
